# Generated by Django 2.0.5 on 2018-10-20 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QandA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='asker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='editors',
            field=models.ManyToManyField(related_name='edits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='followers',
            field=models.ManyToManyField(related_name='question_followees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='topics',
            field=models.ManyToManyField(related_name='questions', to='QandA.Topic'),
        ),
        migrations.AddField(
            model_name='answerrequest',
            name='askee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_asked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answerrequest',
            name='asker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answerrequest',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QandA.Question'),
        ),
        migrations.AddField(
            model_name='answercomment',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QandA.Answer'),
        ),
        migrations.AddField(
            model_name='answercomment',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answercomment',
            name='voters',
            field=models.ManyToManyField(related_name='comment_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='bookmarkers',
            field=models.ManyToManyField(related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='credential',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Credential'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QandA.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='responder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='shareholders',
            field=models.ManyToManyField(related_name='shares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='voters',
            field=models.ManyToManyField(related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='answerrequest',
            unique_together={('asker', 'askee', 'question')},
        ),
    ]
